version: '3.8'

services:
  model-server:
    build: 
      context: ./model_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../model:/app/model
      - ../config.yaml:/app/model/config.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      model-server:
        condition: service_healthy 